#高可用Eureka注册中心
server:
  port: 8080

eureka:
  instance:
    hostname: 101.37.172.37 #配置注册中心的主机名，必须需要和defaultZone中的域名对应
    ip-address: 101.37.172.37 #eureka实例的ip地址
    metadata-map:
      username: zhangwei  #元数据需要英文或者数字，不能为汉字
      password: 99999999999666666 #元数据需要英文或者数字，不能为汉字
  client:
    fetch-registry: true #使注册中心同步注册列表，单注册中心时为false
    registry-fetch-interval-seconds: 5 #设置同步注册列表的时间,默认30秒
    register-with-eureka: true #使注册中心自己注册自己，单注册中心时为false

    service-url:
      defaultZone: http://49.235.67.7:18080/eureka/ #暴露Eureka注册中心的注册地址
