#高可用Eureka注册中心
server:
  port: 8081

eureka:
  instance:
    hostname: peer1 #配置注册中心的主机名，必须需要和defaultZone中的域名对应
    metadata-map:
      username: zhangwei  #元数据需要英文或者数字，不能为汉字
      password: 99999999999666666 #元数据需要英文或者数字，不能为汉字
  client:
    service-url:
      defaultZone: http://peer2:8082/eureka/ #暴露Eureka注册中心的注册地址

spring:
  application:
    name: microservice-eurekaserver #服务名